app:
  services:
    bot-url: ${RAILWAY_SERVICE_ACSPBOT_URL}
spring:
  application:
    name: ACSP Backend
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: acsp
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, readinessIndicator
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]
  health:
    diskspace:
      enabled: false
  metrics:
    tags:
      service: ${RAILWAY_SERVICE_NAME}
      environment: ${RAILWAY_ENVIRONMENT_NAME}
  info:
    java:
      enabled: true
    env:
      enabled: true
    os:
      enabled: true
info:
  railway:
    project_name: ${RAILWAY_PROJECT_NAME}
    environment_name: ${RAILWAY_ENVIRONMENT_NAME}
    service_name: ${RAILWAY_SERVICE_NAME}
    service_url: ${RAILWAY_PUBLIC_DOMAIN}
    replica_id: ${RAILWAY_REPLICA_ID}
    deployment_id: ${RAILWAY_DEPLOYMENT_ID}
server:
  port: 80
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org.springframework.boot.web.embedded: OFF
    org.springframework.boot.web.servlet.context: OFF
    org.apache.catalina: OFF