app:
  services:
    bot-url: ${RAILWAY_SERVICE_ACSPBOT_URL}
spring:
  application:
    name: ACSP Backend
  output:
    ansi:
      enabled: always
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: acsp
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState, readinessIndicator
  endpoints:
    web:
      exposure:
        include: [ "health", "info" ]
  health:
    diskspace:
      enabled: false
server:
  port: 80
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org.springframework.boot.web.embedded: OFF
    org.springframework.boot.web.servlet.context: OFF
    org.apache.catalina: OFF