global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'acsp-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'acsp-bot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['acspbot:80']
  - job_name: 'acsp-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['acspbackend:80']