app:
  config:
    client-id: ${BOT_CLIENT_ID}
    client-secret: ${BOT_CLIENT_SECRET}
    bot-token: ${BOT_TOKEN}
  services:
    backend-url: ${RAILWAY_SERVICE_ACSPBACKEND_URL}
spring:
  application:
    name: ACSP Discord Bot
  output:
    ansi:
      enabled: always
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    diskspace:
      enabled: false
server:
  port: 80
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: off
logging:
  level:
    org.springframework.boot.web.embedded: OFF
    org.springframework.boot.web.servlet.context: OFF
    org.apache.catalina: OFF