name: CI across all ACSP modules

on:
  push:
    branches: [main]
  pull_request:
    branches: [main,develop]
  workflow_dispatch:
jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AcspBackend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Test with Maven
        run: mvn -B clean test verify --file pom.xml
  bot:
    name: Build and Test Discord Bot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AcspBot
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build and Test with Maven
        run: mvn -B clean test verify --file pom.xml